# Generated by Django 5.2.17 on 2026-09-15 10:01

import django.db.models.deletion
import inventory.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('category', models.CharField(max_length=120)),
                ('retired', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='positive_box_number')],
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='open', max_length=16)),
                ('entries', models.JSONField(default=list)),
                ('files', models.JSONField(default=list)),
                ('receipt', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=inventory.models.expiry)),
                ('analyzing_until', models.DateTimeField(null=True)),
                ('analysis_token', models.UUIDField(null=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.box')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('aliases', models.CharField(blank=True, max_length=1000)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('draft_row', models.PositiveIntegerField(null=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.box')),
                ('draft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.draft')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(max_length=30)),
                ('note', models.CharField(blank=True, max_length=2000)),
                ('reporter', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.box')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
            ],
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('draft', 'draft_row'), name='unique_batch_row'),
        ),
    ]
