# Generated by Django 5.2.17 on 2026-09-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_box_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='transcript',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
