# Generated by Django 5.2.17 on 2026-09-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_draft_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='context',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
