# Generated by Django 5.2.17 on 2026-09-16 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_draft_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.box'),
        ),
    ]
